#!/usr/bin/env bash
# ==============================================================================
# deploy-vps.sh — FINAL one-shot provisioning for a FRESH Z.com Ubuntu VPS.
#
# Run ON the VPS as root (paste once, wait, done):
#     bash scripts/prod/deploy-vps.sh
#
# What it does (everything below is idempotent — safe to re-run):
#   0. sanity: run-as-root, config block, docker install (get.docker.com w/ apt fallback)
#   1. /opt/mogok-maung + git clone (URL below; falls back to git pull if present)
#   2. .env.production created from the embedded template when missing
#      (real secrets are generated automatically by go-live — never type them)
#   3. delegates to scripts/prod/go-live.sh:  tls->ssl->deploy->public verify
#
# CONFIG — EDIT THIS BLOCK ------------------------------------------------------
# MUST be a real cloneable URL. Never leave the placeholder in place.
GIT_URL="${GIT_URL:-https://github.com/mokotmaung-lang/mogok-maung-backend.git}"
GIT_BRANCH="${GIT_BRANCH:-main}"
# Public domain pair. " <apex> <api-host>" → apex SPA + api host (api.* name is
# conventional; change BOTH here AND the A-records of that host).
DOMAINS="${DOMAINS:-oddsmyanmar.online api.oddsmyanmar.online}"
# Certbot contact / :health check host (first part of DOMAINS is the SPA apex).
EMAIL="${EMAIL:-admin@oddsmyanmar.online}"
# Expected public A-record values (used for the DNS pre-check warning only).
VPS_IP="${VPS_IP:-203.31.93.52}"
SKIP_PORT_CHECK="${SKIP_PORT_CHECK:-0}"
# --- no edits beyond this line ------------------------------------------------
set -euo pipefail

[ "$(id -u)" -eq 0 ] || { echo "[deploy-vps] run as root: sudo bash scripts/prod/deploy-vps.sh"; exit 1; }

REPO_DIR=/opt/mogok-maung
ENV_FILE="${REPO_DIR}/.env.production"
APEX="${DOMAINS%% *}"
API="${DOMAINS##* }"
RED=$'\e[31m'; GRN=$'\e[32m'; YLW=$'\e[33m'; NC=$'\e[0m'

die() { echo -e "${RED}[deploy-vps]${NC} $*" >&2; exit 1; }
info() { echo -e "${GRN}[deploy-vps]${NC} $*"; }
warn() { echo -e "${YLW}[deploy-vps]${NC} $*"; }

trap 'die "failed at line $LINENO (command: $BASH_COMMAND)"' ERR

case "${GIT_URL}" in
    *your-username*|*your-repo*|https://github.com/your-repo.git|'')
        die "GIT_URL is still a placeholder — edit the CONFIG block at the top of scripts/prod/deploy-vps.sh with the real URL, then push main." ;;
esac

info "configured: DOMAINS=${DOMAINS} EMAIL=${EMAIL} VPS_IP=${VPS_IP}"

# --- 0. Docker ---------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1 || ! docker compose version >/dev/null 2>&1; then
    info "installing docker + compose plugin..."
    apt-get update -y
    apt-get install -y ca-certificates curl gnupg ufw
    if ! curl -fsSL https://get.docker.com | sh; then
        warn "get.docker.com failed — falling back to the docker APT repo..."
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
        apt-get update -y
    fi
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    systemctl enable --now docker
else
    info "docker present: $(docker --version); compose: $(docker compose version --short)"
fi

if command -v ufw >/dev/null 2>&1 && ! ufw status | grep -q "Status: active"; then
    info "enabling ufw (22 + 80,443)..."
    ufw allow OpenSSH
    ufw allow 80,443/tcp
    echo y | ufw enable
fi

# --- 1. Git checkout ----------------------------------------------------------
mkdir -p "${REPO_DIR}"
if [ -z "$(ls -A "${REPO_DIR}")" ]; then
    info "cloning ${GIT_URL} (${GIT_BRANCH})..."
    git clone --branch "${GIT_BRANCH}" --single-branch "${GIT_URL}" "${REPO_DIR}"
elif [ -d "${REPO_DIR}/.git" ]; then
    info "repo present — fetching ${GIT_BRANCH}..."
    git -C "${REPO_DIR}" fetch origin
    git -C "${REPO_DIR}" checkout "${GIT_BRANCH}" 2>/dev/null || git -C "${REPO_DIR}" checkout -b "${GIT_BRANCH}" origin/"${GIT_BRANCH}"
    git -C "${REPO_DIR}" reset --hard "origin/${GIT_BRANCH}"
else
    die "${REPO_DIR} exists but is not a git repo — move it away first (it is not the cloned project)."
fi
cd "${REPO_DIR}"
chmod +x scripts/prod/*.sh

# --- 2. .env.production (created ONLY when missing — never overwrite) --------
if [ ! -f "${ENV_FILE}" ]; then
    info "creating ${ENV_FILE} from template (secrets are generated by go-live)..."
    cat > "${ENV_FILE}" <<EOF
# .env.production — bootstrapped by deploy-vps.sh. Secrets autofilled by go-live.sh.

# --- Database (PostgreSQL) ---
DB_HOST=127.0.0.1
DB_PORT=5432
DB_USER=bet_admin
DB_PASSWORD=CHANGE_ME_STRONG_DB_PASSWORD
DB_NAME=myanmar_bet_prod
DB_SSLMODE=require

# --- API / auth ---
JWT_SECRET=
PORT=8081
DOMAIN_NAME=${API}

# --- Realtime cache (Redis) ---
REDIS_ADDR=127.0.0.1:6379
REDIS_PASSWORD=CHANGE_ME_STRONG_REDIS_PASSWORD

# --- Settlement / agent queue (RabbitMQ) ---
RABBITMQ_USER=CHANGE_ME_BROKER_USER
RABBITMQ_PASS=CHANGE_ME_STRONG_BROKER_PASSWORD
AMQP_URL=amqp://CHANGE_ME_BROKER_USER:CHANGE_ME_STRONG_BROKER_PASSWORD@127.0.0.1:5672/
SETTLEMENT_QUEUE=match_settlement_queue
AGENT_UNIT_REQUEST_QUEUE=agent_unit_request_queue

# --- Bootstrap SUPER_ADMIN ---
BOOT_ADMIN_USER=superadmin
BOOT_ADMIN_PASS=CHANGE_ME_BOOTSTRAP_ADMIN_PASSWORD

# --- Bot hooks (optional) ---
TELEGRAM_WEBHOOK_SECRET=
VIBER_AUTH_TOKEN=

# --- Admin Web ---
BACKEND_URL=https://${API}
NEXT_PUBLIC_API_URL=https://${API}
NEXT_PUBLIC_WS_URL=wss://${API}
EOF
    chmod 600 "${ENV_FILE}"
elif ! grep -qE '^DOMAIN_NAME=' "${ENV_FILE}"; then
    die "${ENV_FILE} exists but is missing DOMAIN_NAME — fix it manually before continuing."
fi

# --- 3. Delegate to go-live (docker idempotent, secrets, DNS, TLS, SSL, deploy, verify)
info "handing off to go-live.sh (this is the long step — docker build + SSL + health)..."
EMAIL="${EMAIL}" DOMAINS="${DOMAINS}" VPS_IP="${VPS_IP}" SKIP_PORT_CHECK="${SKIP_PORT_CHECK}" \
    bash scripts/prod/go-live.sh

info "done. Check: curl -fsS https://${API}/health  →  ok"